setup.ilm.enabled: false
packetbeat.interfaces.device: any
packetbeat.protocols:
  - type: dhcpv4
    ports: [67, 68]
  - type: dns
    ports: [53]
  - type: http
    ports: [80, 8080, 8081, 5000, 8002]
  - type: tls
    ports: [443, 993, 995, 5223, 8443, 8883, 9243]
output.elasticsearch:
  hosts:
    ['https://vpc-staging-game-uxkfmxrpt742ihwgawvebv7mji.eu-west-2.es.amazonaws.com:443']
