name: Automatic Code Review
on: [pull_request]

jobs:
  Linting:
    name: Automatic code linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          locale: 'US'
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
      - name: dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          dotenv_linter_flags: --skip UnorderedKey
