# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  City:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
      - name: Use Node.js v12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.19.0'
      - name: Clean install BE dependencies
        run: yarn --cwd entry_points/city_api ci
      - name: Run BE tests
        run: yarn --cwd entry_points/city_api test
  User:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
      - name: Use Node.js v12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.19.0'
      - name: Clean install BE dependencies
        run: yarn --cwd entry_points/user_api ci
      - name: Run BE tests
        run: yarn --cwd entry_points/user_api test
